rokubiminis:
#  - name: ft_sensor0
#    configuration_file: rokubimini_sensor.yaml
#    product_code: 1
#    port: /dev/ttyUSB0
#    baud_rate: 460800
  - name:                     ft_sensor0
    configuration_file:       rokubimini_sensor.yaml
    product_code:             2
    ethercat_bus:             enp0s31f6
    ethercat_address:         1


